name: tudu
description: Aplikacja Tu-Du 2

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  build_runner: ^2.4.6
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.1.1
  flutter_hooks: ^0.20.2
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.1.14
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^11.1.2
  google_fonts: ^6.1.0
  injectable: ^2.3.1
  injectable_generator: ^2.4.0
  intl: ^0.18.1
  intl_utils: ^2.8.4
  isar: ^3.1.0+1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: Translation
  arb_dir: lib/core/translations/l10n
  output_dir: lib/core/translations/generated
  main_locale: pl
